algolia/instantsearch-android

instantsearch/src/main/java/com/algolia/instantsearch/events/NumericRefinementEvent.java, instantsearch/src/main/java/com/algolia/instantsearch/events/RefinementEvent.java, instantsearch/src/main/java/com/algolia/instantsearch/helpers/Searcher.java, instantsearch/src/main/java/com/algolia/instantsearch/model/NumericRefinement.java, instantsearch/src/main/java/com/algolia/instantsearch/ui/views/filters/NumericSelector.java, instantsearch/src/test/java/com/algolia/instantsearch/model/NumericRefinementTest.java
First implementation of refinement events, allowing widgets to stay in sync.
=> NumericRefinementEvents - base for widget syncing

README.md
For consistency with other readmes
=> docs(readme): add links to other InstantSearch flavours

instantsearch/src/main/java/com/algolia/instantsearch/helpers/Searcher.java
Enable search from an `Intent`, such as the system's voice search feature sending an `INTENT_SEARCH` with a `QUERY`.
=> feat(Searcher): Voice search API

.travis.yml
- Use new `travis_latest` group
=> Update travis setup

instantsearch/src/main/java/com/algolia/instantsearch/helpers/Searcher.java, instantsearch/src/main/java/com/algolia/instantsearch/transformer/SearchResultsHandler.java, instantsearch/src/main/java/com/algolia/instantsearch/transformer/SearchTransformer.java, instantsearch/src/main/java/com/algolia/instantsearch/transformer/Transformable.java
=> feat(custombackend): Change the Searcher to use a searchable index instead of concrete implementation

docgen/src/concepts.md, docgen/src/data/communityHeader.json, docgen/src/examples.md, docgen/src/getting-started.md, docgen/src/multi-index.md, docgen/src/widgets.md, docgen/yarn.lock
To check the Guide with rendering:
- `git fetch --all && git checkout origin/docs/guideMultiIndex`
- `./scripts/serve.sh`
- `open localhost:3000/multi-index.html`
For convenience, you can also see screenshots below.
@robertmogos and @spinach, would love your feedback on the content (is it as simple as possible, straightforward, do you see things worth mentioning I overlooked?)
@Jerska, I'd appreciate if you can check the section on Query Suggestions and let me know if you see any issue / ways I can improve it or make it clearer :slightly_smiling_face: 
----
=> docs: Guide for multi index and query suggestions

docgen/src/javadoc/constant-values.html, docgen/src/widgets.md, instantsearch/src/main/java/com/algolia/instantsearch/ui/databinding/BindingHelper.java
Make highlightColor usable again.
=> fix(highlightColor): typo in BindingAdapter

instantsearch/src/main/java/com/algolia/instantsearch/ui/views/Hits.java
=> fix(Hits): don't process bindings when they are none

instantsearch/build.gradle, instantsearch/src/main/java/com/algolia/instantsearch/helpers/Highlighter.java
Update dependencies, solving #94.
=> chore: update deps

core/src/main/java/com/algolia/instantsearch/core/model/Errors.java, ui/src/main/java/com/algolia/instantsearch/ui/databinding/BindingHelper.java
More explicit error messages: 
- Widget with no id: `Your View for attribute null must have an android:id`
- Hit view with no id: `Your View for attribute image must have an android:id`
- Widget with no id: `Your View (Hits) must have an android:id.` 
- Hit view with no id: `Your View (AppCompatImageView) for attribute 'image' must have an android:id`
=> refactor(BindingHelper): Log class name on error

fastlane/Fastfile
See #113, third round :upside_down_face:
=> fix(Fastfile): fix git_commit files path

fastlane/Fastfile
=> refactor(Fastfile): Remove build_type from bintrayUpload

fastlane/Fastfile
=> fix(Fastfile): Force add_git_tag

fastlane/Fastfile
=> fix(Fastfile): Force push_git_tags

fastlane/Fastfile
=> fix(Fastfile): Use right variable

fastlane/Fastfile
=> chore(Fastfile): Branch before creating PR

fastlane/Fastfile
=> chore(Fastfile): Define var for Token, used for PR

fastlane/Fastfile
=> fix(Fastfile): Push commit on PR branch

fastlane/Fastfile
=> chore(Fastfile): Correct variable ordering

CHANGELOG.md, README.md, properties.gradle
Please check the files before merging in case I've overidden something accidentally.
=> Deploying new minor version 1.15.0

ui/src/main/java/com/algolia/instantsearch/ui/views/Hits.java
**Summary**
- Remove local `LayoutManager`, see #110.
**Result**: Demonstrated in theory, will ensure tests run fine.
=> fix(Hits): Remove local LayoutManager, fixes #110

CHANGELOG.md, README.md, fastlane/Fastfile
Fixes erroneous `'` added to the `implementation` Usage line.
Will be demonstrated with next release.
=> chore: Fix Readme's usage generation

README.md, properties.gradle
Add missing release commit (tag `1.15.1` was on 1f6416ae :thinking:).
=> chore(release): Version 1.15.1 [ci skip]

CHANGELOG.md, README.md, properties.gradle
Please check the files before merging in case I've overidden something accidentally.
=> chore(release): Version 1.15.2 [ci skip]

README.md
=> docs(README): Fix HEAD [ci skip]

core/build.gradle, core/src/main/java/com/algolia/instantsearch/core/helpers/QuerySuggestionsContentProvider.java, libraries.gradle, ui/build.gradle, ui/src/main/res/layout/layout_checkbox.xml, ui/src/main/res/layout/refinement_row.xml
- Update Algolia API Client to 3.27.0
- Remove unused dependencies
- Fix potential NPE
- Use default locale when lowercasing Query suggestions
=> Fix/dependencies, potential NPE, default locale

CHANGELOG.md, README.md, properties.gradle
Please check the files before merging in case I've overidden something accidentally.
=> chore(release): Version 1.15.3 [ci skip]

core/src/commonMain/kotlin/com/algolia/instantsearch/core/hits/HitsConnection.kt, helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/hits/HitsArrayAdapter.kt, helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/hits/HitsArrayAdapterConnection.kt, helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/hits/HitsViewConnection.kt, helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/searchbox/SearchBoxAutoCompleteTextView.kt, helper/src/androidTest/kotlin/searchbox/TestSearchBoxAutoCompleteTextView.kt
=> Add SearchBoxAutoCompleteTextView

buildSrc/src/main/kotlin/dependency/Library.kt, buildSrc/src/main/kotlin/dependency/network/Coroutines.kt, buildSrc/src/main/kotlin/dependency/network/Ktor.kt, buildSrc/src/main/kotlin/dependency/script/AtomicFu.kt, buildSrc/src/main/kotlin/dependency/ui/AndroidCore.kt, buildSrc/src/main/kotlin/dependency/ui/MaterialDesign.kt, buildSrc/src/main/kotlin/dependency/ui/Paging.kt, buildSrc/src/main/kotlin/dependency/ui/RecyclerView.kt, gradle.properties, helper/build.gradle.kts, helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/list/SearcherMultipleIndexDataSource.kt, helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/list/SearcherSingleIndexDataSource.kt
Update the library to target Android API 30 (R) and androidx dependencies versions
=> chore(android): support Android API 30 (R)

CHANGELOG.md, core/src/commonMain/kotlin/com/algolia/instantsearch/core/tree/Extensions.kt, core/src/commonMain/kotlin/com/algolia/instantsearch/core/tree/Node.kt, core/src/commonTest/kotlin/tree/TestExtensions.kt, helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/hierarchical/Extensions.kt, helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/hierarchical/HierarchicalConnectionSearcher.kt, helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/hierarchical/HierarchicalItem.kt, helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/hierarchical/HierarchicalPresenterImpl.kt
Add selection capability to the hierarchical tree nodes
=> feat(hierachical): support selectable nodes

CHANGELOG.md, buildSrc/src/main/kotlin/dependency/Library.kt, core/src/commonMain/kotlin/com/algolia/instantsearch/core/number/range/NumberRangeViewModel.kt, helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/filter/range/FilterRangeConnection.kt, helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/filter/range/FilterRangeConnectionSearcher.kt, helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/filter/range/internal/FilterRangeConnectionSearcherImpl.kt, helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/filter/range/internal/Mapper.kt, helper/src/commonTest/kotlin/filter/range/TestFilterRangeConnectSearcher.kt
Add dynamic behavior to numerical sliders by introducing a new connection between the `FilterRangeViewModel` and `Searcher`
=> feat(filter): dynamic range filters

helper/src/androidTest/kotlin/documentation/widget/DocHitsMultiple.kt, helper/src/androidTest/kotlin/documentation/widget/DocHitsPagingSingle.kt
=> chore(doc): update DiffUtil implementation

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/dependency/lib/AtomicFu.kt, buildSrc/src/main/kotlin/dependency/plugin/AndroidTools.kt, buildSrc/src/main/kotlin/dependency/plugin/GradleMavenPublish.kt, instantsearch-android-core/build.gradle.kts
=> chore: update to kotlin 1.4.10

buildSrc/src/main/kotlin/Library.kt, instantsearch-android-core/src/main/kotlin/com/algolia/instantsearch/core/subscription/Subscription.kt, instantsearch-android/src/main/java/com/algolia/instantsearch/helper/android/searchbox/SearchBoxViewAppCompat.kt, instantsearch-android/src/main/java/com/algolia/instantsearch/helper/customdata/QueryRuleCustomDataConnection.kt, instantsearch-android/src/main/java/com/algolia/instantsearch/helper/customdata/QueryRuleCustomDataConnector.kt, instantsearch-android/src/main/java/com/algolia/instantsearch/helper/customdata/QueryRuleCustomDataPresenter.kt, instantsearch-android/src/main/java/com/algolia/instantsearch/helper/customdata/QueryRuleCustomDataViewModel.kt, instantsearch-android/src/main/java/com/algolia/instantsearch/helper/customdata/internal/QueryRuleCustomDataConnectionMultipleIndex.kt, instantsearch-android/src/main/java/com/algolia/instantsearch/helper/customdata/internal/QueryRuleCustomDataConnectionSingleIndex.kt, instantsearch-android/src/main/java/com/algolia/instantsearch/helper/extension/KSerializer.kt, instantsearch-android/src/main/java/com/algolia/instantsearch/helper/extension/Utils.kt, instantsearch-android/src/test/java/customdata/TestQueryRuleCustomData.kt
Widget implementation: **Query Rule Custom Data**
=> feat: query rule custom data widget

CHANGELOG.md, buildSrc/src/main/kotlin/dependency/network/Coroutines.kt, buildSrc/src/main/kotlin/dependency/network/Ktor.kt
- Kotlin 1.4.21
- Kotlin Coroutines 1.4.2
- Ktor 1.5.1
=> chore(dependencies): update kotlin, coroutines and ktor

CHANGELOG.md, build.gradle.kts, buildSrc/src/main/kotlin/Library.kt, buildSrc/src/main/kotlin/dependency/plugin/Dokka.kt, gradle/gradle-maven-publish.gradle, instantsearch-android-core/build.gradle.kts, instantsearch-android/build.gradle.kts
| Related Issue     | Fix #224
=> chore(release): migrate from bintray to maven central

build.gradle.kts, buildSrc/src/main/kotlin/dependency/network/Ktor.kt
Update dependencies:
- Kotlin `1.4.31`
- Ktor `1.5.2`
=> chore(deps): Kotlin 1.4.31 and Ktor 1.5.2

buildSrc/src/main/kotlin/Library.kt, buildSrc/src/main/kotlin/dependency/compose/Compose.kt, instantsearch-android/build.gradle.kts, instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/searchbox/SearchBox.kt, instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/searchbox/internal/SearchBoxComponents.kt
=> fix(search-box): use `ImeAction.Search` and expose new parameters

fastlane/Fastfile
Update CI/CD to publish to maven central.
=> chore(cd): fix CI/CD publish workflow

gradle/libs.versions.toml, instantsearch/src/commonTest/kotlin/searchbox/TestSearchBoxConnectSearcher.kt
=> chore: Compose `1.0.0-rc02`

build.gradle.kts, instantsearch/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/filter/facet/dynamic/DynamicFacetListAdapter.kt, instantsearch/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/filter/facet/dynamic/DynamicFacetListViewHolder.kt
=> refactor: generics in dynamic facet list adapter

build.gradle.kts, gradle/libs.versions.toml
* Compose `1.0.0`
* AGP `7.0.0`
* Paging-compose to `1.0.0-alpha12`
* android-core to `1.6.0`
* appcompat to `1.3.1`
* recyclerview to `1.2.1`
* material to `1.4.0`
=> chore: dependencies versions bump

build.gradle.kts, gradle/libs.versions.toml
* Compose to `1.0.1`
* Kotlin to `1.5.21`
* Algolia API client to `1.9.2`
* Ktor to `1.6.2`
=> chore: update compose to 1.0.1

instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/number/relevantsort/RelevantSortState.kt, instantsearch-compose/src/test/kotlin/com/algolia/instantsearch/compose/number/RelevantSortStateTest.kt
=> fix: add missing `RelevantSortPriorityState`

instantsearch-insights/build.gradle.kts, instantsearch-insights/src/androidTest/kotlin/com/algolia/instantsearch/insights/InsightsTest.kt, instantsearch-insights/src/androidTest/kotlin/com/algolia/instantsearch/insights/TestInsightsEventUploader.kt, instantsearch-insights/src/commonMain/kotlin/com/algolia/instantsearch/insights/internal/uploader/InsightsEventUploader.kt
| Related Issue     | Fix #256 
Ignore events older or equal to 4 days at upload time.
=> fix(insights): ignore events older than 4 days

instantsearch/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/list/SearcherSingleIndexDataSource.kt
| Related Issue     | Fix #259 
Fix pagination for single index data source: next page not being loaded.
=> fix(search): single index paging

build.gradle.kts, gradle/libs.versions.toml, instantsearch-core/build.gradle.kts, instantsearch-insights/build.gradle.kts, instantsearch/build.gradle.kts
* Kotlin `1.5.31`
* Ktor `1.6.5`
* Compose `1.0.5`
* Paging Compose: `1.0.0-alpha14`
=> chore: kotlin 1.5.31

gradle/libs.versions.toml
=> chore: update ktor to 1.6.6

CHANGELOG.md, gradle.properties, gradle/libs.versions.toml, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/helper/extension/Telemetry.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/helper/searcher/Extensions.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/helper/searcher/SearcherAnswers.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/helper/searcher/SearcherForFacets.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/helper/searcher/SearcherMultipleIndex.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/helper/searcher/SearcherSingleIndex.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/helper/searcher/facets/internal/DefaultFacetsSearcher.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/helper/searcher/hits/internal/DefaultHitsSearcher.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/helper/searcher/internal/withUserAgent.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/helper/searcher/multi/internal/DefaultMultiSearcher.kt, instantsearch/src/commonTest/kotlin/telemetry/TestTelemetry.kt
=> fix: telemetry header

gradle/wrapper/gradle-wrapper.properties
=> chore: update gradle to 7.3.2

instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/helper/searcher/facets/internal/DefaultFacetsSearcher.kt
=> fix(searcher): `setQuery` function to set `facetQuery` field

gradle/libs.versions.toml, instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/searchbox/SearchBox.kt, instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/searchbox/internal/SearchBoxComponents.kt, instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/searchbox/internal/SearchBoxStateImpl.kt
=> refactor:  search box `enabled` param

gradle/wrapper/gradle-wrapper.properties
=> chore: update gradle to 7.3.3

build.gradle.kts
=> chore: update AGP to `7.1.0`

instantsearch-core/src/commonMain/kotlin/com/algolia/instantsearch/core/hits/HitsConnection.kt, instantsearch-core/src/commonMain/kotlin/com/algolia/instantsearch/core/hits/internal/HitsConnectionView.kt
=> feat(searcher): connect to past hits

build.gradle.kts, gradle/libs.versions.toml
=> chore: update gradle plugin to `7.1.3`

gradle/libs.versions.toml
=> chore: update kotlin api client to `1.13.0`

gradle/libs.versions.toml
=> chore: update ktor to `1.6.8`

examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/App.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/directory/Directory.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/guides/compose/MainViewModel.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/guides/gettingstarted/MyViewModel.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/guides/insights/InsightsActivity.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/androidview/Demo.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/androidview/filter/facet/dynamic/DynamicFacetShowcase.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/compose/Demo.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/compose/filter/facet/DynamicFacetShowcase.kt, extensions/coroutines-extensions/src/commonMain/kotlin/com/algolia/instantsearch/coroutines/Subscription.kt, extensions/coroutines-extensions/src/commonTest/kotlin/TestSubscription.kt, gradle/libs.versions.toml, instantsearch-insights/src/androidMain/kotlin/com/algolia/instantsearch/insights/Insights.kt, instantsearch-insights/src/commonMain/kotlin/com/algolia/instantsearch/insights/internal/data/distant/InsightsHttpRepository.kt, instantsearch-insights/src/commonMain/kotlin/com/algolia/instantsearch/insights/internal/extension/Insights.kt, instantsearch/src/commonTest/kotlin/Client.kt, settings.gradle.kts
| BC breaks?        | yes
- Update Kotlin API client to version `2.0`
- Update the code and examples to match the API changes
=> refact: update to kotlin api client 2.0

examples/android/README.md, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/guides/gettingstarted/FacetFragment.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/guides/gettingstarted/GettingStartedGuide.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/guides/gettingstarted/MyViewModel.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/guides/gettingstarted/ProductAdapter.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/guides/gettingstarted/ProductFragment.kt, examples/android/src/main/res/layout/activity_getting_started.xml, extensions/android-loading/README.md, extensions/android-paging3/README.md, extensions/coroutines-extensions/README.md
=> chore(guides): update code snippets

instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/searcher/facets/FacetsSearcher.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/searcher/facets/SearchForFacetQuery.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/searcher/facets/internal/DefaultFacetsSearcher.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/searcher/hits/HitsSearcher.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/searcher/hits/SearchForQuery.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/searcher/hits/internal/DefaultHitsSearcher.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/searcher/multi/MultiSearcher.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/searcher/multi/internal/DefaultMultiSearcher.kt
* Default `triggerSearchFor` to `All`
* Searchers: expose `coroutineDispatcher` param
=> refact: default `triggerSearchFor`

examples/android/build.gradle, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/guides/insights/ListItemAdapter.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/androidview/customdata/QueryRuleCustomDataShowcase.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/androidview/highlighting/HighlightingViewHolder.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/androidview/list/movie/MovieViewHolder.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/androidview/list/movie/MovieViewHolderNested.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/androidview/list/product/ProductAdapter.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/compose/customdata/QueryRuleCustomDataShowcase.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/compose/ui/component/MoviesList.kt, examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/compose/ui/component/ProductList.kt
=> refact(examples): use coil for image loading

extensions/android-loading/build.gradle.kts, extensions/android-paging3/build.gradle.kts, extensions/android-paging3/src/main/kotlin/com/algolia/instantsearch/android/paging3/internal/SearcherPagingSource.kt, instantsearch-compose/build.gradle.kts, instantsearch/src/androidMain/kotlin/com/algolia/instantsearch/extension/Console.kt, instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/extension/Console.kt, instantsearch/src/jvmMain/kotlin/com/algolia/instantsearch/extension/Console.kt
Paging search operations were failing in silence, this PR adds logging on fail.
=> chore(paging): add logging warning on fail

examples/android/build.gradle, examples/androidtv/build.gradle
=> fix(examples): update compose compiler version

gradle/libs.versions.toml
=> chore: algolia api kotlin client `2.1.1`

gradle/libs.versions.toml
=> chore(compose): update compiler version to 1.3.1

gradle.properties, gradle/libs.versions.toml, instantsearch-insights/build.gradle.kts, instantsearch/build.gradle.kts
=> chore(deps): update compose compiler to `1.4.0`

CHANGELOG.md, gradle.properties
| New feature?      | no
Prepare release 3.2.0
=> chore: prepare release 3.2.0

instantsearch-utils/src/commonJvm/kotlin/com/algolia/instantsearch/util/uuid.kt
| New feature?      | no
Fix lint issue in the `uuid.kt` file
Lint check doesn't pass successfully.
=> chore: fix lint issue in the uuid file

CHANGELOG.md, gradle.properties
| New feature?      | no
Prepare release 3.2.1
=> chore: prepare release 3.2.1

CHANGELOG.md, gradle.properties
=> chore: prepare release 3.3.0

gradle/libs.versions.toml
=> chore(client): update algolia API kotlin client to `2.1.10`

examples/android/build.gradle, extensions/android-paging3/src/main/kotlin/com/algolia/instantsearch/android/paging3/Paginator.kt
=> fix(paging): default initial load size value
