algolia/instantsearch-android

- instantsearch/src/main/java/com/algolia/instantsearch/helpers/Searcher.java
- instantsearch/src/main/java/com/algolia/instantsearch/ui/views/SearchBox.java
This was a required change to support the following interaction:
1. Search is triggered from another Activity to the SearchableActivity
2. `SearchBox` is initialized, but is in a `Menu` so is not attached to window yet
3. `Searcher` gets the search `Intent` and triggers the search, sending a `QueryTextChangeEvent`
4. The `SearchBox` gets attached to the screen, but does not display the query
With this change, the `SearchBox` registers at step 2, ensuring it updates its query.
I made sure to avoid double registration on EventBus.
> SearchBox: Register for events at init

- build.gradle
- gradle.properties
- instantsearch/build.gradle
- instantsearch/src/main/java/com/algolia/instantsearch/helpers/Searcher.java
Hi Algolia,
Some explanations of my commits:
1. https://github.com/algolia/instantsearch-android/commit/e625f50d17cbfe7ee8f5e34fe116db0caba5e4ad
I tried to update my project to use data binding v2, but encountered an error.
The fix solution is to use data binding v2 in your SDK.
2. https://github.com/algolia/instantsearch-android/commit/585c62fb3798ffc917189d17fd3d3781af0450f2
I use lower version of glide, which has a conflict with your SDK, because the SDK expose its dependencies to me.
So I should do this in my gradle file:
```
api('com.algolia:instantsearch-android:1.8.2') {
exclude group: 'com.github.bumptech.glide'
}
```
It may be better if simply we do not expose these dependencies of your SDK to users.
3. https://github.com/algolia/instantsearch-android/commit/ba12166820292420d726e9 …
> Improvements

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- instantsearch/src/main/java/com/algolia/instantsearch/helpers/Searcher.java
Hello @PLNech 
In my last pull request https://github.com/algolia/instantsearch-android/pull/83 I forgot to update android build tool. Therefore the line of code which activates data binding v2 does not work. So here is a new PR to fix it. Sorry for the mistake 
c.f. https://developer.android.com/topic/libraries/data-binding/start#preview-compiler
> Use gradle 4.4 with android build tool 3.1.3

- instantsearch/src/main/java/com/algolia/instantsearch/searchclient/DefaultSearchClient.java
- instantsearch/src/main/java/com/algolia/instantsearch/searchclient/SearchClient.java
- instantsearch/src/main/java/com/algolia/instantsearch/searchclient/SearchResultsHandler.java
- instantsearch/src/main/java/com/algolia/instantsearch/searchclient/Transformable.java
- Rename from `SerachTransformer` to `SearchClient` (same for interfaces)
- Add `searchDisjunctiveFaceting` and `searchForFacetValues` method (basic) support.
- Abstract calling the map functions away from the 3rd party dev
- Introduce DefaultSearchClient for default cases when just need to forward Algolia requests/responses without any transformation
- Bug in SearchClient where it should take a `Request` instead of `Void`
> feat(searchclient): Improve the searchClient

- instantsearch/build.gradle
The change in b960f46 actually prevents apps to implement event `Subscribe`rs, unless they pull themselves the EventBus library.
As this would risk a mismatch between the library's version and the app's, I would rather expose EventBus as an `api` (users can always strip them from the released app using Proguard if they really want to get rid of the 50k EventBus adds).
> fix(gradle): Expose EventBus to enable listening to events

- fastlane/Fastfile
- ui/build.gradle
**Summary**
1. Mark `appcompat` as explicit dependency in `ui`, as implicitely pulling `project(':core')` was failing in Jitpack-based test builds
2. Fix Jitpack's URL missing `.github` prefix
**Result**
Before 1.:
```                                                                            ^
symbol:   class SearchView
location: package android.support.v7.widget
16 errors
FAILURE: Build failed with an exception.
```
After 1.:
```
BUILD SUCCESSFUL in 25s
```
2. Will be tested on next client test after this PR is merged.
> chore: Fix Jitpack dependent build

- release.gradle
Uses new bintrayv.gradle with GPG signing and MavenCentral Sync (requiring the former):
```diff
diff --git a/gradle/bintrayv.gradle b/gradle/bintrayv.gradle
index 17ab9bc..7287827 100644
--- a/gradle/bintrayv.gradle
+++ b/gradle/bintrayv.gradle
@@ -127,6 +127,14 @@ bintray {
desc = "Version $VERSION"
released = new Date()
vcsTag = VERSION
+            
+            gpg {
+                sign = true
+            }
+            mavenCentralSync {
+                user = System.getenv('NEXUS_USERNAME')
+                password = System.getenv('NEXUS_PASSWORD')
+            }      
}
}
}
```
- Should restore sync in Maven Central. Will release latest changes (#137) to confirm that!
> chore: Use bintrayv with gpg & mavenCentralSync

- LICENSE
Changes license from `MIT` to `Apache V2`.
> chore(LICENSE): Move ISv2 to Apache v2

- LICENSE.md
Changes license from `MIT` to `Apache V2`.
> chore(LICENSE.md): Move ISv1 to Apache V2

- README.md
- core/src/main/java/com/algolia/instantsearch/core/helpers/Searcher.java
- ui/src/main/java/com/algolia/instantsearch/ui/helpers/InstantSearch.java
Announces deprecation of ISv1 in favor of ISv2.
Deprecation message:
> The V1 version of InstantSearch has been **deprecated in favor of V2**: the new version offers a better architecture, more features, and is easier to customize. See our [migration guide][1]  - the V1 will only **get security fixes**, while **new Algolia features are implemented in V2**.
- Marks `Searcher` and `InstantSearch` as deprecated
- Links to the (to be written) [Migration Guide][1]
[1]: https://deploy-preview-3505--algolia-doc.netlify.com/doc/guides/building-search-ui/upgrade-guides/android/
> chore: Deprecate v1.

- buildSrc/src/main/kotlin/dependency/Library.kt
- helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/list/SearcherSingleIndexDataSource.kt
This happens because in the `LoadInitial` of the DataSource, we execute a search and block the thread. 
When a new request is made while the current search is being made, InstantSearch will try to `invalidate` the pagedList, but this will fail as the LoadInitial is still ongoing and doing some work. 
It follows that we don't get the latest query that the user entered in the search bar.
> fix(pagedList): Potential fix when typing quickly in searchBar

- build.gradle.kts
- buildSrc/src/main/kotlin/dependency/network/AlgoliaClient.kt
- buildSrc/src/main/kotlin/dependency/script/AndroidTools.kt
Fix #198 by updating algoliasearch-client that causes the crash
Build produced without errors: 
```
BUILD SUCCESSFUL in 40s
60 actionable tasks: 60 executed
18:30:00: Task execution finished 'assemble'.
```
> Attempt to fix #198 : updated algolia-client, AGP and Kotlin versions

- CHANGELOG.md
- helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/highlighting/Extensions.kt
- helper/src/androidTest/kotlin/highlighting/TestExtensions.kt
`HighlightedString.toSpannedString(ParcelableSpan)` used the same object to apply spans. 
However, a given `CharacterStyle` can only applied to a single region of a given Spanned.
> fix(SpannedString): apply the correct spans in toSpannedString extension 

- CHANGELOG.md
- buildSrc/src/main/kotlin/dependency/Library.kt
- gradle/wrapper/gradle-wrapper.properties
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/relateditems/MatchingPattern.kt
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/relateditems/SearcherConnectionRelatedItems.kt
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/relateditems/internal/FilterFacetAndID.kt
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/relateditems/internal/OptionalFilter.kt
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/relateditems/internal/RelatedItemsConnectionView.kt
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/relateditems/internal/extensions/FilterState.kt
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/relateditems/internal/extensions/Indexable.kt
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/relateditems/internal/extensions/MatchingPattern.kt
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/relateditems/internal/extensions/SearcherSingleIndex.kt
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/relateditems/internal/extensions/Unquote.kt
- helper/src/commonTest/kotlin/relatedItems/Product.kt
- helper/src/commonTest/kotlin/relatedItems/TestMachingPattern.kt
- helper/src/commonTest/kotlin/relatedItems/TestSearcherConnectionRelatedItems.kt
Related Items widget, follows same [iOS](https://www.algolia.com/doc/api-reference/widgets/configure-related-items/ios/) and [js](https://www.algolia.com/doc/api-reference/widgets/configure-related-items/js/) implementations.
```kotlin
@Serializable
data class Product(
val name: String,
val brand: String,
val type: String,
val categories: List<String>,
val image: String,
override val objectID: ObjectID
) : Indexable
val matchingPatterns: List<MatchingPattern<Product>> = listOf(
MatchingPattern(Attribute("brand"), 1, Product::brand),
MatchingPattern(Attribute("categories"), 2, Product::categories)
)
val index = client.initIndex(IndexName("stub"))
val searcher = SearcherSingleIndex(index)
val connection = ConnectionHandler()
val relatedItemsAdapter = ProductAdapter() …
```
> Related items widget implementation

- helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/sortby/SortByConnection.kt
- helper/src/androidMain/kotlin/com/algolia/instantsearch/helper/android/sortby/SortByConnectionPagedList.kt
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/searchbox/SearchBoxConnection.kt
This connection is useful when using a _SortByConnector / SortByViewModel_ with a paginated list.
Each selection event of the _SortBy_ widget invalidates the datasource to refresh the underlying data with the proper index.
> Connect SortByViewModel with PagedList

- CHANGELOG.md
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/hierarchical/HierarchicalConnectionSearcher.kt
- helper/src/commonMain/kotlin/com/algolia/instantsearch/helper/hierarchical/HierarchicalViewModel.kt
Filter unexpected sub-nodes in the tree. 
Solves the cases of expanding multiple nodes at the same time.
> fix(hierarchical): Remove unexpected sub-nodes from the tree

- README.md
Update the R8/Proguard readme section to match the latest changes and refer to [Algolia Kotlin Client](https://github.com/algolia/algoliasearch-client-kotlin#r8--proguard-rules).
> chore: update r8/proguard readme section

- instantsearch-android/src/main/java/com/algolia/instantsearch/helper/android/list/SearcherMultipleIndexDataSource.kt
- instantsearch-android/src/main/java/com/algolia/instantsearch/helper/android/list/SearcherSingleIndexDataSource.kt
New `triggerSearchForQuery` parameter to enable/disable `PagedList` loading:
* Single Index: `(Query) -> Boolean)`
* Multiple Index: `(List<IndexQuery>) -> Boolean`
Example with Single Index and `triggerSearchForQuery = { query -> query.query?.isNotEmpty() == true }`:
Fixes: #220
> feat(search): enable/disable loading in PagedLists

- README.md
> chore(publishing): remove bintray from README.md

- CHANGELOG.md
- instantsearch-android-core/src/main/kotlin/com/algolia/instantsearch/core/subscription/Subscription.kt
- instantsearch-android-core/src/main/kotlin/com/algolia/instantsearch/core/subscription/SubscriptionEvent.kt
- instantsearch-android-core/src/main/kotlin/com/algolia/instantsearch/core/subscription/SubscriptionValue.kt
`LinkedHashSet` is not thread-safe. Modifying it while iterating over it causes a `ConcurrentModificationException` to be thrown. This can typically happen when subscribing/unsubscribing to a `Subscription` instance while notifying all subscriptions.
`CopyOnWriteArraySet` is useful for the case where the number of elements is generally small and read-only operations vastly outnumber mutative operations. This seems to match our use case here.
_An alternative can be using a mutex._
> fix(subscription): make subscriptions list thread-safe

- buildSrc/src/main/kotlin/Library.kt
- instantsearch-android/src/main/java/com/algolia/instantsearch/helper/android/list/RetryablePageKeyedDataSource.kt
- instantsearch-android/src/main/java/com/algolia/instantsearch/helper/android/list/SearcherMultipleIndexDataSource.kt
- instantsearch-android/src/main/java/com/algolia/instantsearch/helper/android/list/SearcherSingleIndexDataSource.kt
Add two functions to data source to retry the latest failed `loadInitial` or `loadAfter` operation:
* `retry`: takes advantage of a `CoroutineScope` and a `CoroutineDispatcher` (uses `Dispatchers.IO` by default)
*  `retryAsync`: uses a `CoroutineDispatcher` as an `Executor`
> feat(paging): add retry functions to paging data source

- buildSrc/src/main/kotlin/dependency/compose/Compose.kt
- buildSrc/src/main/kotlin/dependency/compose/Paging.kt
- buildSrc/src/main/kotlin/dependency/plugin/AndroidTools.kt
Update Compose to [1.0.0-rc01](https://developer.android.com/jetpack/androidx/releases/compose-ui#1.0.0-rc01)
> chore: update Compose to 1.0.0-rc01

- gradle/libs.versions.toml
- instantsearch-compose/build.gradle.kts
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/filter/facet/FacetListConnector.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/filter/facet/internal/FacetListConnectionPager.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/filter/state/FilterStateConnection.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/filter/state/internal/FilterStateConnectionPaginator.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/list/Paginator.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/list/internal/SearcherMultipleIndexPagingSource.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/list/internal/SearcherPaginator.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/list/internal/SearcherSingleIndexPagingSource.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/searchbox/SearchBoxConnector.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/searchbox/internal/SearchBoxConnectionPaginator.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/sortby/SortByConnection.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/sortby/internal/SortByConnectionPaginator.kt
- instantsearch-insights/build.gradle.kts
- instantsearch/build.gradle.kts
since it based on paging-compose alpha versions
The [paging-compose](https://developer.android.com/jetpack/androidx/releases/paging#paging_compose_version_100_2) library is still in alpha stage; we are marking the APIs depending on it as `@ExperimentalInstantSearch`.
> refactor(paging): mark paginator as experimental

- instantsearch-core/build.gradle.kts
- instantsearch-utils/src/commonMain/kotlin/com/algolia/instantsearch/Annotations.kt
- instantsearch-utils/src/commonMain/kotlin/com/algolia/instantsearch/encode/Gzip.kt
- instantsearch/build.gradle.kts
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/helper/extension/Telemetry.kt
- instantsearch/src/commonTest/kotlin/telemetry/TestTelemetry.kt
> refactor: rename `Internal` annotation to `InternalInstantSearch`

- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/filter/numeric/comparison/FilterComparisonComputeBounds.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/filter/range/internal/Mapper.kt
Add missing `setBoundsFromFacetStats` to `FilterComparisonConnector`
> feat: add `setBoundsFromFacetStats` to `FilterComparisonConnector`

- instantsearch/src/androidMain/kotlin/com/algolia/instantsearch/extension/Log.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/extension/Utils.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/searcher/internal/SearcherExceptionHandler.kt
- instantsearch/src/jvmMain/kotlin/com/algolia/instantsearch/extension/printError.kt
* Android: prints to `Log.e`
* JVM: standard error output
> chore: print searcher exception stacktrace

- instantsearch-insights/src/androidMain/kotlin/com/algolia/instantsearch/insights/internal/InsightsController.kt
- instantsearch-insights/src/androidTest/kotlin/com/algolia/instantsearch/insights/InsightsTest.kt
- instantsearch-insights/src/commonMain/kotlin/com/algolia/instantsearch/insights/FilterTrackable.kt
- instantsearch-insights/src/commonMain/kotlin/com/algolia/instantsearch/insights/HitsAfterSearchTrackable.kt
- instantsearch-insights/src/commonMain/kotlin/com/algolia/instantsearch/insights/Insights.kt
- instantsearch-insights/src/commonMain/kotlin/com/algolia/instantsearch/insights/internal/InsightsController.kt
- instantsearch-insights/src/commonMain/kotlin/com/algolia/instantsearch/insights/internal/extension/Insights.kt
- instantsearch-insights/src/commonMain/kotlin/com/algolia/instantsearch/insights/internal/extension/InsightsEvent.kt
| New feature?      | yes    
Add `Insights.Configuration(generateTimestamps: Long)` parameter.
Defines if the timestamps of the events should be automatically attributed if not provided while calling the event capturing function. If set to `false`, the events will be sent without timestamp value and will be automatically attributed on the server, which may affect the accuracy of the events.
> feat: insights timestamps generation configuration

- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/searcher/SearcherAnswers.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/searcher/SearcherConnection.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/searcher/internal/SearcherAnswersConnectionFilterState.kt
- instantsearch/src/commonTest/kotlin/searcher/Extensions.kt
- instantsearch/src/commonTest/kotlin/telemetry/TestTelemetry.kt
Deprecate Answers widget: `SearcherAnswers`.
> refactor: deprecate `SearcherAnswers`

- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/categorieshits/SearchScreen.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/multipleindex/SearchScreen.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/suggestions/categories/SearchScreen.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/suggestions/hits/SearchScreen.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/suggestions/query/SearchScreen.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/suggestions/recent/SearchScreen.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/voice/SearchScreen.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/guides/compose/SearchScreen.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/compose/directory/DirectoryScreen.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/compose/ui/component/SearchBox.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/compose/ui/component/TopBar.kt
- examples/androidtv/src/main/java/com/algolia/instantsearch/examples/androidtv/SearchScreen.kt
- examples/androidtv/src/main/java/com/algolia/instantsearch/examples/androidtv/ui/SearchBox.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/searchbox/SearchBox.kt
- instantsearch-compose/src/main/java/com/algolia/instantsearch/compose/searchbox/SearchBoxState.kt
Current implementation of `SearchBox` UI is hardly customizable, and depends on material.  
In this PR we deprecate the current implementation, with guidelines how to easily implement it.
> chore: deprecate compose `SearchBox`

- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/compose/hierarchical/HierarchicalShowcase.kt
- instantsearch-core/src/commonMain/kotlin/com/algolia/instantsearch/core/tree/Extensions.kt
- instantsearch-core/src/commonMain/kotlin/com/algolia/instantsearch/core/tree/internal/Tree.kt
- instantsearch-core/src/commonTest/kotlin/tree/TestHierarchicalNode.kt
- instantsearch-core/src/commonTest/kotlin/tree/TestTreeConnectView.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/hierarchical/internal/Extensions.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/hierarchical/internal/HierarchicalConnectionSearcher.kt
| Related Issue     | FX-1551
While generating nodes items, facets with any separator will be split.
Example: `A > B - C` with `>` as separator with two levels: 
* with current behavior: 
- lvl0: `A` 
- lvl1: `B`
- lvl2: `C`
* with the fix:
- lvl0: `A`
- lvl1: `B - C`
> fix(filters): hierarchical items split seperator

- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/hierarchical/HierarchicalPath.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/hierarchical/HierarchicalViewModel.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/hierarchical/internal/HierarchicalConnectionFilterState.kt
- instantsearch/src/commonTest/kotlin/hierarchical/TestHierarchicalConnectFilterState.kt
| Related Issue     | FX-1567
Calling `onSelectionChanged` on already selected item doesn't introduce any change to the hierarchical tree.
The expected behavior would be to deselect the item and update the hierarchical tree.
> fix(hierarchical): deselect item

- instantsearch-core/src/commonMain/kotlin/com/algolia/instantsearch/core/subscription/SubscriptionValue.kt
- instantsearch-core/src/commonMain/kotlin/com/algolia/instantsearch/core/subscription/internal/SubscriptionOnce.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/filter/range/FilterRangeConnector.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/filter/range/internal/FilterRangeConnectionFilterState.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/filter/range/internal/FilterRangeConnectionSearcherImpl.kt
| Related Issue     | FX-1587
Fix bounds/range initialization to match the following:
| Bounds/Range | connectSearcher | Behavior                                                                                                       |
|--------------|-----------------|----------------------------------------------------------------------------------------------------------------|
| Yes          | Yes             | The bounds retrieved from the first search operation, the range will match the value set using the constructor |
| No           | Yes             | The bounds retrieved from the first search operation, the range will …
> fix(range): filter range bounds init

- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/Theme.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/categorieshits/MainActivity.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/categorieshits/MainViewModel.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/categorieshits/Product.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/categorieshits/SearchScreen.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/multipleindex/MainActivity.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/multipleindex/MainViewModel.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/multipleindex/SearchScreen.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/compose/ui/component/SearchBox.kt
> chore(examples): update multisearch code examples

- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/filter/facet/dynamic/DynamicFacetConnection.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/filter/facet/dynamic/DynamicFacetListConnector.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/filter/facet/dynamic/DynamicFacetListViewModel.kt
- instantsearch/src/commonMain/kotlin/com/algolia/instantsearch/filter/facet/dynamic/internal/DynamicFacetListConnectionFilterState.kt
Add `defaultSelectionMode` and `defaultFilterOperator` parameters to DynamicFacetList components to customize their default behaviour. It will replace the hardcoded single selection, and filter group type.
> feat(DynamicFacetList): add default selection & faceting parameters

- docs/guide/Migration_2.x_3.x.md
| Related Issue     | Fix #...  
This PR updates the v2 to v3 migration guide to correctly label the tables with the relevant version numbers.
> chore: correctly reference migration versions in v2 to v3 guide

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .tool-versions
- examples/android/build.gradle
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/codex/voice/MainActivity.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/guides/extension/SearchView.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/guides/insights/InsightsActivity.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/androidview/Demo.kt
- examples/android/src/main/kotlin/com/algolia/instantsearch/examples/android/showcase/compose/ui/component/RatingBar.kt
- extensions/android-loading/build.gradle.kts
- extensions/android-paging3/build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- instantsearch-compose/build.gradle.kts
- instantsearch-insights/build.gradle.kts
- instantsearch-utils/build.gradle.kts
- instantsearch-utils/src/commonJvm/kotlin/com/algolia/instantsearch/util/uuid.kt
- instantsearch/build.gradle.kts
- instantsearch/src/androidUnitTest/kotlin/instrumented/InstrumentedTest.kt
Update the project dependencies to be compatible with Android Studio Flamingo (AGP 8.x)
> feat: update the project to AGP 8.x (flamingo)
